notifications:
  email: false

language: csharp
mono: none
dotnet: 2.1

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test ./test/bayonet.Api.Tests/
  - dotnet test ./test/bayonet.Client.Tests/
  - dotnet test ./test/bayonet.Core.Tests/